#ifndef BOOST_ASIO_DETAIL_CONFIG_HPP
#define BOOST_ASIO_DETAIL_CONFIG_HPP

#if defined(BOOST_ASIO_STANDALONE)
#define BOOST_ASIO_DISABLE_BOOST_ALIGN 1
#define BOOST_ASIO_DISABLE_BOOST_ARRAY 1
#define BOOST_ASIO_DISABLE_BOOST_ASSERT 1
#define BOOST_ASIO_DISABLE_BOOST_BIND 1
#define BOOST_ASIO_DISABLE_BOOST_CHRONO 1
#define BOOST_ASIO_DISABLE_BOOST_DATE_TIME 1
#define BOOST_ASIO_DISABLE_BOOST_LIMITS 1
#define BOOST_ASIO_DISABLE_BOOST_REGEX 1
#define BOOST_ASIO_DISABLE_BOOST_STATIC_CONSTANT 1
#define BOOST_ASIO_DISABLE_BOOST_THROW_EXCEPTION 1
#define BOOST_ASIO_DISABLE_BOOST_WORKAROUND 1
#else // defined(BOOST_ASIO_STANDALONE)
// Boost.Config library is available.
#include <boost/config.hpp>
#include <boost/version.hpp>
#define BOOST_ASIO_HAS_BOOST_CONFIG 1
#endif // defined(BOOST_ASIO_STANDALONE)

#endif